services:
  postgres:
    container_name: spring_security_asymmetric
    image: postgres:latest
    environment:
      POSTGRES_USER: lokesh
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
      POSTGRES_DB: Security_Demo-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: