spring:
  application:
    name: SpringSecurityAsymmetricEncryption
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/{DB_NAME}
    username: lokesh
    password: 12345
    Driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      accessTokenExpiration: 86400000 #24 hours for testing
      refreshTokenExpiration: 604800000

